apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prd
resources:
  - ../../base
  - namespace.yaml
patches:
  - path: ingressroute-host.yaml
    target:
      group: traefik.io
      version: v1alpha1
      kind: IngressRoute
      name: hello-kubernetes
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: hello-kubernetes
      spec:
        template:
          spec:
            containers:
            - name: hello-kubernetes
              env:
              - name: MESSAGE
                value: "prd - application v1.0"
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: hello-kubernetes-canary
      spec:
        template:
          spec:
            containers:
            - name: hello-kubernetes
              env:
              - name: MESSAGE
                value: "prd - application v2.0"
