apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes
  namespace: default
  labels:
    app: hello-kubernetes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
        track: stable
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.10
        env:
        - name: MESSAGE
          value: "application A"
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes-canary
  namespace: default
  labels:
    app: hello-kubernetes-canary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-kubernetes-canary
  template:
    metadata:
      labels:
        app: hello-kubernetes-canary
        track: canary
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.10
        env:
        - name: MESSAGE
          value: "application B"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-stable
  namespace: default
spec:
  type: ClusterIP
  selector:
    track: stable
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-canary
  namespace: default
spec:
  type: ClusterIP
  selector:
    track: canary
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: hello-kubernetes-weighted
  namespace: default
spec:
  weighted:
    services:
    - name: hello-kubernetes-stable
      port: 80
      weight: 75
    - name: hello-kubernetes-canary
      port: 80
      weight: 25
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hello-kubernetes
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`hello-kubernetes.192.168.123.125.nip.io`)
      kind: Rule
      services:
        - name: hello-kubernetes-weighted
          kind: TraefikService
